categorical_columns:
  Education:
  - Graduate
  - Postgraduate
  - Undergraduate
  Family_Size:
  - 1
  - 3
  - 2
  - 4
  - 5
  Living_With:
  - Alone
  - Partner
  - Divorced
  - Widow
  Marital_Status:
  - Single
  - Together
  - Married
  - Divorced
  - Widow
  - Alone
  - Absurd
  - YOLO
  Total_Offsprings:
  - 0
  - 2
  - 1
  - 3
numerical_columns:
- Income
- Recency
- Wines
- Fruits
- Meat
- Fish
- Sweet
- Gold
- DealsPurchases
- Web
- Catalog
- Store
- WebVisitsMonth
- Complain
- Age
- Total_Amount
- Frequency
- Total_purchases
- online_purchase_ratio
